// Generated by leapfrog codegen: do not edit by hand
// This file is automatically generated. Do not edit this file. If you want to make changes
// edit leapfrog json files in `leapfrog-core/model_schemas` and run `uv run ./src/main.py` inside
// the `codegen` folder.

#pragma once

#include <concepts>

namespace leapfrog::internal {

template<typename ModelVariant>
concept MV = requires (ModelVariant mv) {
  { mv.run_demographic_projection } -> std::convertible_to<bool>;
  { mv.run_hiv_simulation } -> std::convertible_to<bool>;
  { mv.use_coarse_stratification } -> std::convertible_to<bool>;
  { mv.run_child_model } -> std::convertible_to<bool>;
  { mv.run_spectrum_model } -> std::convertible_to<bool>;
  { mv.run_goals } -> std::convertible_to<bool>;
};


template<typename Config>
concept RunDemographicProjection = MV<typename Config::ModelVariant> && Config::ModelVariant::run_demographic_projection;

template<typename Config>
concept RunHivSimulation = MV<typename Config::ModelVariant> && Config::ModelVariant::run_hiv_simulation;

template<typename Config>
concept UseCoarseStratification = MV<typename Config::ModelVariant> && Config::ModelVariant::use_coarse_stratification;

template<typename Config>
concept RunChildModel = MV<typename Config::ModelVariant> && Config::ModelVariant::run_child_model;

template<typename Config>
concept RunSpectrumModel = MV<typename Config::ModelVariant> && Config::ModelVariant::run_spectrum_model;

template<typename Config>
concept RunGoals = MV<typename Config::ModelVariant> && Config::ModelVariant::run_goals;

}  // namespace leapfrog::internal
