// Generated by leapfrog codegen: do not edit by hand
// This file is automatically generated. Do not edit this file. If you want to make changes
// edit leapfrog json files in `leapfrog-core/model_schemas` and run `uv run ./src/main.py` inside
// the `codegen` folder.

#pragma once

namespace leapfrog {

struct DemographicProjection {
  static constexpr bool run_demographic_projection = true;
  static constexpr bool run_hiv_simulation = false;
  static constexpr bool use_coarse_stratification = false;
  static constexpr bool run_child_model = false;
  static constexpr bool run_spectrum_model = false;
  static constexpr bool run_goals = false;
};
struct HivFullAgeStratification {
  static constexpr bool run_demographic_projection = true;
  static constexpr bool run_hiv_simulation = true;
  static constexpr bool use_coarse_stratification = false;
  static constexpr bool run_child_model = false;
  static constexpr bool run_spectrum_model = false;
  static constexpr bool run_goals = false;
};
struct HivCoarseAgeStratification {
  static constexpr bool run_demographic_projection = true;
  static constexpr bool run_hiv_simulation = true;
  static constexpr bool use_coarse_stratification = true;
  static constexpr bool run_child_model = false;
  static constexpr bool run_spectrum_model = false;
  static constexpr bool run_goals = false;
};
struct ChildModel {
  static constexpr bool run_demographic_projection = true;
  static constexpr bool run_hiv_simulation = true;
  static constexpr bool use_coarse_stratification = false;
  static constexpr bool run_child_model = true;
  static constexpr bool run_spectrum_model = false;
  static constexpr bool run_goals = false;
};
struct CoarseChildModel {
  static constexpr bool run_demographic_projection = true;
  static constexpr bool run_hiv_simulation = true;
  static constexpr bool use_coarse_stratification = true;
  static constexpr bool run_child_model = true;
  static constexpr bool run_spectrum_model = false;
  static constexpr bool run_goals = false;
};
struct Spectrum {
  static constexpr bool run_demographic_projection = true;
  static constexpr bool run_hiv_simulation = true;
  static constexpr bool use_coarse_stratification = false;
  static constexpr bool run_child_model = true;
  static constexpr bool run_spectrum_model = true;
  static constexpr bool run_goals = false;
};
struct Goals {
  static constexpr bool run_demographic_projection = true;
  static constexpr bool run_hiv_simulation = true;
  static constexpr bool use_coarse_stratification = false;
  static constexpr bool run_child_model = true;
  static constexpr bool run_spectrum_model = false;
  static constexpr bool run_goals = true;
};

}  // namespace leapfrog
