// Generated by leapfrog codegen: do not edit by hand
// This file is automatically generated. Do not edit this file. If you want to make changes
// edit leapfrog json files in `leapfrog-core/model_schemas` and run `uv run ./src/main.py` inside
// the `codegen` folder.

unit LeapfrogInterface;

interface

uses SysUtils, GBFixedArray;

{$ALIGN 8}
type
  LeapfrogOptions = record
  public
    // Year projection started e.g. 1970
    projStartYear: Integer;
    // Year projection end e.g. 2030
    projEndYear: Integer;
    // Time index to start ART initiation e.g. 34 would mean in 2004
    tsArtStart: Integer;
    // Projection period 0 for calendar year, 1 for mid year
    projPeriod: Integer;
end;

{$ALIGN 8}
type
  LeapfrogDemProjParamsView = record
  private
    basePop: PDouble;
    basePopLength: Integer;
    survivalProbability: PDouble;
    survivalProbabilityLength: Integer;
    netMigration: PDouble;
    netMigrationLength: Integer;
    ageSpecificFertilityRate: PDouble;
    ageSpecificFertilityRateLength: Integer;
    birthsSexProp: PDouble;
    birthsSexPropLength: Integer;
    totalFertilityRate: PDouble;
    totalFertilityRateLength: Integer;
end;

type
  LeapfrogDemProjParams = class
  public
    basePop: TGBFixedArray<Double>;
    survivalProbability: TGBFixedArray<Double>;
    netMigration: TGBFixedArray<Double>;
    ageSpecificFertilityRate: TGBFixedArray<Double>;
    birthsSexProp: TGBFixedArray<Double>;
    totalFertilityRate: TGBFixedArray<Double>;
    function getView(): LeapfrogDemProjParamsView;
    procedure writeToDisk(dir: string);
    Destructor Destroy; override;
end;

{$ALIGN 8}
type
  LeapfrogDemProjStateView = record
  private
    pTotpop: PDouble;
    pTotpopLength: Integer;
    pDeathsBackgroundTotpop: PDouble;
    pDeathsBackgroundTotpopLength: Integer;
    births: PDouble;
    birthsLength: Integer;
end;

type
  LeapfrogDemProjState = class
  public
    pTotpop: TGBFixedArray<Double>;
    pDeathsBackgroundTotpop: TGBFixedArray<Double>;
    births: TGBFixedArray<Double>;
    function getView(): LeapfrogDemProjStateView;
    procedure writeToDisk(dir: string);
    Destructor Destroy; override;
end;

{$ALIGN 8}
type
  LeapfrogHivAdultParamsView = record
  private
    incidenceModelChoice: Integer;
    incidenceModelChoiceLength: Integer;
    inputAdultIncidenceRate: PDouble;
    inputAdultIncidenceRateLength: Integer;
    transmissionRateHts: PDouble;
    transmissionRateHtsLength: Integer;
    initialIncidence: Double;
    initialIncidenceLength: Integer;
    epidemicStartHts: Integer;
    epidemicStartHtsLength: Integer;
    relativeInfectiousnessArt: Double;
    relativeInfectiousnessArtLength: Integer;
    incidenceRateRatioAge: PDouble;
    incidenceRateRatioAgeLength: Integer;
    incidenceRateRatioSex: PDouble;
    incidenceRateRatioSexLength: Integer;
    cd4Mortality: PDouble;
    cd4MortalityLength: Integer;
    cd4Progression: PDouble;
    cd4ProgressionLength: Integer;
    cd4InitialDistribution: PDouble;
    cd4InitialDistributionLength: Integer;
    scaleCd4Mortality: Integer;
    scaleCd4MortalityLength: Integer;
    idxHmElig: PInteger;
    idxHmEligLength: Integer;
    artMortality: PDouble;
    artMortalityLength: Integer;
    artMortalityTimeRateRatio: PDouble;
    artMortalityTimeRateRatioLength: Integer;
    cd4NonaidsExcessMort: PDouble;
    cd4NonaidsExcessMortLength: Integer;
    artNonaidsExcessMort: PDouble;
    artNonaidsExcessMortLength: Integer;
    dropoutRecoverCd4: Integer;
    dropoutRecoverCd4Length: Integer;
    dropoutRate: PDouble;
    dropoutRateLength: Integer;
    adultsOnArt: PDouble;
    adultsOnArtLength: Integer;
    adultsOnArtIsPercent: PInteger;
    adultsOnArtIsPercentLength: Integer;
    initiationMortalityWeight: Double;
    initiationMortalityWeightLength: Integer;
    hArtStageDur: PDouble;
    hArtStageDurLength: Integer;
    pagIncidpop: Integer;
    pagIncidpopLength: Integer;
    pidxIncidpop: Integer;
    pidxIncidpopLength: Integer;
    fertMultByAge: PDouble;
    fertMultByAgeLength: Integer;
    fertMultOffArt: PDouble;
    fertMultOffArtLength: Integer;
    fertMultOnArt: PDouble;
    fertMultOnArtLength: Integer;
    localAdjFactor: Double;
    localAdjFactorLength: Integer;
    pwidHivposNonaidsMortality: Double;
    pwidHivposNonaidsMortalityLength: Integer;
    pwidPropHivpop: PDouble;
    pwidPropHivpopLength: Integer;
    pwidSexRatio: PDouble;
    pwidSexRatioLength: Integer;
end;

type
  LeapfrogHivAdultParams = class
  public
    incidenceModelChoice: Integer;
    inputAdultIncidenceRate: TGBFixedArray<Double>;
    transmissionRateHts: TGBFixedArray<Double>;
    initialIncidence: Double;
    epidemicStartHts: Integer;
    relativeInfectiousnessArt: Double;
    incidenceRateRatioAge: TGBFixedArray<Double>;
    incidenceRateRatioSex: TGBFixedArray<Double>;
    cd4Mortality: TGBFixedArray<Double>;
    cd4Progression: TGBFixedArray<Double>;
    cd4InitialDistribution: TGBFixedArray<Double>;
    scaleCd4Mortality: Integer;
    idxHmElig: TGBFixedArray<Integer>;
    artMortality: TGBFixedArray<Double>;
    artMortalityTimeRateRatio: TGBFixedArray<Double>;
    cd4NonaidsExcessMort: TGBFixedArray<Double>;
    artNonaidsExcessMort: TGBFixedArray<Double>;
    dropoutRecoverCd4: Integer;
    dropoutRate: TGBFixedArray<Double>;
    adultsOnArt: TGBFixedArray<Double>;
    adultsOnArtIsPercent: TGBFixedArray<Integer>;
    initiationMortalityWeight: Double;
    hArtStageDur: TGBFixedArray<Double>;
    pagIncidpop: Integer;
    pidxIncidpop: Integer;
    fertMultByAge: TGBFixedArray<Double>;
    fertMultOffArt: TGBFixedArray<Double>;
    fertMultOnArt: TGBFixedArray<Double>;
    localAdjFactor: Double;
    pwidHivposNonaidsMortality: Double;
    pwidPropHivpop: TGBFixedArray<Double>;
    pwidSexRatio: TGBFixedArray<Double>;
    function getView(): LeapfrogHivAdultParamsView;
    procedure writeToDisk(dir: string);
    Destructor Destroy; override;
end;

{$ALIGN 8}
type
  LeapfrogHivAdultStateView = record
  private
    pHivpop: PDouble;
    pHivpopLength: Integer;
    pDeathsBackgroundHivpop: PDouble;
    pDeathsBackgroundHivpopLength: Integer;
    hHivpop: PDouble;
    hHivpopLength: Integer;
    hArtpop: PDouble;
    hArtpopLength: Integer;
    hHivDeathsNoArt: PDouble;
    hHivDeathsNoArtLength: Integer;
    hDeathsExcessNonaidsNoArt: PDouble;
    hDeathsExcessNonaidsNoArtLength: Integer;
    pInfections: PDouble;
    pInfectionsLength: Integer;
    hHivDeathsArt: PDouble;
    hHivDeathsArtLength: Integer;
    hDeathsExcessNonaidsOnArt: PDouble;
    hDeathsExcessNonaidsOnArtLength: Integer;
    hArtInitiation: PDouble;
    hArtInitiationLength: Integer;
    pHivDeaths: PDouble;
    pHivDeathsLength: Integer;
    pDeathsExcessNonaids: PDouble;
    pDeathsExcessNonaidsLength: Integer;
    pNetMigrationHivpop: PDouble;
    pNetMigrationHivpopLength: Integer;
    hivBirthsByMatAge: PDouble;
    hivBirthsByMatAgeLength: Integer;
    hivBirths: PDouble;
    hivBirthsLength: Integer;
    prevalence15to49Hts: PDouble;
    prevalence15to49HtsLength: Integer;
    incidence15to49Hts: PDouble;
    incidence15to49HtsLength: Integer;
    artcoverage15to49Hts: PDouble;
    artcoverage15to49HtsLength: Integer;
end;

type
  LeapfrogHivAdultState = class
  public
    pHivpop: TGBFixedArray<Double>;
    pDeathsBackgroundHivpop: TGBFixedArray<Double>;
    hHivpop: TGBFixedArray<Double>;
    hArtpop: TGBFixedArray<Double>;
    hHivDeathsNoArt: TGBFixedArray<Double>;
    hDeathsExcessNonaidsNoArt: TGBFixedArray<Double>;
    pInfections: TGBFixedArray<Double>;
    hHivDeathsArt: TGBFixedArray<Double>;
    hDeathsExcessNonaidsOnArt: TGBFixedArray<Double>;
    hArtInitiation: TGBFixedArray<Double>;
    pHivDeaths: TGBFixedArray<Double>;
    pDeathsExcessNonaids: TGBFixedArray<Double>;
    pNetMigrationHivpop: TGBFixedArray<Double>;
    hivBirthsByMatAge: TGBFixedArray<Double>;
    hivBirths: TGBFixedArray<Double>;
    prevalence15to49Hts: TGBFixedArray<Double>;
    incidence15to49Hts: TGBFixedArray<Double>;
    artcoverage15to49Hts: TGBFixedArray<Double>;
    function getView(): LeapfrogHivAdultStateView;
    procedure writeToDisk(dir: string);
    Destructor Destroy; override;
end;

{$ALIGN 8}
type
  LeapfrogHivChildParamsView = record
  private
    hcNosocomialInfectionsByAge: PDouble;
    hcNosocomialInfectionsByAgeLength: Integer;
    hc1Cd4Dist: PDouble;
    hc1Cd4DistLength: Integer;
    hc1Cd4Mort: PDouble;
    hc1Cd4MortLength: Integer;
    hc2Cd4Mort: PDouble;
    hc2Cd4MortLength: Integer;
    hc1Cd4Prog: PDouble;
    hc1Cd4ProgLength: Integer;
    hc2Cd4Prog: PDouble;
    hc2Cd4ProgLength: Integer;
    ctxVal: PDouble;
    ctxValLength: Integer;
    hcArtEligAge: PInteger;
    hcArtEligAgeLength: Integer;
    hcArtEligCd4: PInteger;
    hcArtEligCd4Length: Integer;
    hcArtMortRr: PDouble;
    hcArtMortRrLength: Integer;
    hc1ArtMort: PDouble;
    hc1ArtMortLength: Integer;
    hc2ArtMort: PDouble;
    hc2ArtMortLength: Integer;
    hcArtIsperc: PInteger;
    hcArtIspercLength: Integer;
    hcArtVal: PDouble;
    hcArtValLength: Integer;
    hcArtInitDist: PDouble;
    hcArtInitDistLength: Integer;
    pmtct: PDouble;
    pmtctLength: Integer;
    verticalTransmissionRate: PDouble;
    verticalTransmissionRateLength: Integer;
    pmtctTransmissionRate: PDouble;
    pmtctTransmissionRateLength: Integer;
    pmtctDropout: PDouble;
    pmtctDropoutLength: Integer;
    pmtctInputIsPercent: PInteger;
    pmtctInputIsPercentLength: Integer;
    breastfeedingDurationArt: PDouble;
    breastfeedingDurationArtLength: Integer;
    breastfeedingDurationNoArt: PDouble;
    breastfeedingDurationNoArtLength: Integer;
    infantPop: PDouble;
    infantPopLength: Integer;
    matHivBirths: PDouble;
    matHivBirthsLength: Integer;
    matPrevInput: PInteger;
    matPrevInputLength: Integer;
    propLt200: PDouble;
    propLt200Length: Integer;
    propGte350: PDouble;
    propGte350Length: Integer;
    ctxValIsPercent: PInteger;
    ctxValIsPercentLength: Integer;
    hcArtIsAgeSpec: PInteger;
    hcArtIsAgeSpecLength: Integer;
    abortion: PDouble;
    abortionLength: Integer;
    patientsReallocated: PDouble;
    patientsReallocatedLength: Integer;
    hcArtLtfu: PDouble;
    hcArtLtfuLength: Integer;
    adultFemaleInfections: PDouble;
    adultFemaleInfectionsLength: Integer;
    adultFemaleHivnpop: PDouble;
    adultFemaleHivnpopLength: Integer;
    totalBirths: PDouble;
    totalBirthsLength: Integer;
    ctxEffect: PDouble;
    ctxEffectLength: Integer;
    hcArtStart: Integer;
    hcArtStartLength: Integer;
    hcAgeSpecificFertilityRate: PDouble;
    hcAgeSpecificFertilityRateLength: Integer;
end;

type
  LeapfrogHivChildParams = class
  public
    hcNosocomialInfectionsByAge: TGBFixedArray<Double>;
    hc1Cd4Dist: TGBFixedArray<Double>;
    hc1Cd4Mort: TGBFixedArray<Double>;
    hc2Cd4Mort: TGBFixedArray<Double>;
    hc1Cd4Prog: TGBFixedArray<Double>;
    hc2Cd4Prog: TGBFixedArray<Double>;
    ctxVal: TGBFixedArray<Double>;
    hcArtEligAge: TGBFixedArray<Integer>;
    hcArtEligCd4: TGBFixedArray<Integer>;
    hcArtMortRr: TGBFixedArray<Double>;
    hc1ArtMort: TGBFixedArray<Double>;
    hc2ArtMort: TGBFixedArray<Double>;
    hcArtIsperc: TGBFixedArray<Integer>;
    hcArtVal: TGBFixedArray<Double>;
    hcArtInitDist: TGBFixedArray<Double>;
    pmtct: TGBFixedArray<Double>;
    verticalTransmissionRate: TGBFixedArray<Double>;
    pmtctTransmissionRate: TGBFixedArray<Double>;
    pmtctDropout: TGBFixedArray<Double>;
    pmtctInputIsPercent: TGBFixedArray<Integer>;
    breastfeedingDurationArt: TGBFixedArray<Double>;
    breastfeedingDurationNoArt: TGBFixedArray<Double>;
    infantPop: TGBFixedArray<Double>;
    matHivBirths: TGBFixedArray<Double>;
    matPrevInput: TGBFixedArray<Integer>;
    propLt200: TGBFixedArray<Double>;
    propGte350: TGBFixedArray<Double>;
    ctxValIsPercent: TGBFixedArray<Integer>;
    hcArtIsAgeSpec: TGBFixedArray<Integer>;
    abortion: TGBFixedArray<Double>;
    patientsReallocated: TGBFixedArray<Double>;
    hcArtLtfu: TGBFixedArray<Double>;
    adultFemaleInfections: TGBFixedArray<Double>;
    adultFemaleHivnpop: TGBFixedArray<Double>;
    totalBirths: TGBFixedArray<Double>;
    ctxEffect: TGBFixedArray<Double>;
    hcArtStart: Integer;
    hcAgeSpecificFertilityRate: TGBFixedArray<Double>;
    function getView(): LeapfrogHivChildParamsView;
    procedure writeToDisk(dir: string);
    Destructor Destroy; override;
end;

{$ALIGN 8}
type
  LeapfrogHivChildStateView = record
  private
    hc1Hivpop: PDouble;
    hc1HivpopLength: Integer;
    hc2Hivpop: PDouble;
    hc2HivpopLength: Integer;
    hc1Artpop: PDouble;
    hc1ArtpopLength: Integer;
    hc2Artpop: PDouble;
    hc2ArtpopLength: Integer;
    hc1NoartAidsDeaths: PDouble;
    hc1NoartAidsDeathsLength: Integer;
    hc2NoartAidsDeaths: PDouble;
    hc2NoartAidsDeathsLength: Integer;
    hc1ArtAidsDeaths: PDouble;
    hc1ArtAidsDeathsLength: Integer;
    hc2ArtAidsDeaths: PDouble;
    hc2ArtAidsDeathsLength: Integer;
    hcArtInit: PDouble;
    hcArtInitLength: Integer;
    hcArtNeedInit: PDouble;
    hcArtNeedInitLength: Integer;
    ctxNeed: PDouble;
    ctxNeedLength: Integer;
    infectionByType: PDouble;
    infectionByTypeLength: Integer;
    mtctBySourceTr: PDouble;
    mtctBySourceTrLength: Integer;
    mtctBySourceWomen: PDouble;
    mtctBySourceWomenLength: Integer;
    mtctBySourceHcInfections: PDouble;
    mtctBySourceHcInfectionsLength: Integer;
    pmtctCoverageAtDelivery: PDouble;
    pmtctCoverageAtDeliveryLength: Integer;
end;

type
  LeapfrogHivChildState = class
  public
    hc1Hivpop: TGBFixedArray<Double>;
    hc2Hivpop: TGBFixedArray<Double>;
    hc1Artpop: TGBFixedArray<Double>;
    hc2Artpop: TGBFixedArray<Double>;
    hc1NoartAidsDeaths: TGBFixedArray<Double>;
    hc2NoartAidsDeaths: TGBFixedArray<Double>;
    hc1ArtAidsDeaths: TGBFixedArray<Double>;
    hc2ArtAidsDeaths: TGBFixedArray<Double>;
    hcArtInit: TGBFixedArray<Double>;
    hcArtNeedInit: TGBFixedArray<Double>;
    ctxNeed: TGBFixedArray<Double>;
    infectionByType: TGBFixedArray<Double>;
    mtctBySourceTr: TGBFixedArray<Double>;
    mtctBySourceWomen: TGBFixedArray<Double>;
    mtctBySourceHcInfections: TGBFixedArray<Double>;
    pmtctCoverageAtDelivery: TGBFixedArray<Double>;
    function getView(): LeapfrogHivChildStateView;
    procedure writeToDisk(dir: string);
    Destructor Destroy; override;
end;

{$ALIGN 8}
type
  LeapfrogSpectrumParamsView = record
  private
end;

type
  LeapfrogSpectrumParams = class
  public
    function getView(): LeapfrogSpectrumParamsView;
    procedure writeToDisk(dir: string);
    Destructor Destroy; override;
end;

{$ALIGN 8}
type
  LeapfrogSpectrumStateView = record
  private
    pDeathsNonaidsArtpop: PDouble;
    pDeathsNonaidsArtpopLength: Integer;
    pDeathsNonaidsHivpop: PDouble;
    pDeathsNonaidsHivpopLength: Integer;
    pExcessDeathsNonaidsOnArt: PDouble;
    pExcessDeathsNonaidsOnArtLength: Integer;
    pExcessDeathsNonaidsNoArt: PDouble;
    pExcessDeathsNonaidsNoArtLength: Integer;
end;

type
  LeapfrogSpectrumState = class
  public
    pDeathsNonaidsArtpop: TGBFixedArray<Double>;
    pDeathsNonaidsHivpop: TGBFixedArray<Double>;
    pExcessDeathsNonaidsOnArt: TGBFixedArray<Double>;
    pExcessDeathsNonaidsNoArt: TGBFixedArray<Double>;
    function getView(): LeapfrogSpectrumStateView;
    procedure writeToDisk(dir: string);
    Destructor Destroy; override;
end;

{$ALIGN 8}
type
  LeapfrogGoalsParamsView = record
  private
    goalsBaseYearIdx: Integer;
    goalsBaseYearIdxLength: Integer;
    epiStartYear: Integer;
    epiStartYearLength: Integer;
    epiMonthsInPrimary: Double;
    epiMonthsInPrimaryLength: Integer;
    bBalanceSexActs: Integer;
    bBalanceSexActsLength: Integer;
    epiInitialPulse: Double;
    epiInitialPulseLength: Integer;
    bCondomProp: PDouble;
    bCondomPropLength: Integer;
    bBehavProperties: PDouble;
    bBehavPropertiesLength: Integer;
    bSexActs: PDouble;
    bSexActsLength: Integer;
    bNumPartners: PDouble;
    bNumPartnersLength: Integer;
    bIncrRecruit: PDouble;
    bIncrRecruitLength: Integer;
    bMarriedProp: PDouble;
    bMarriedPropLength: Integer;
    bAgeFirstSex: PDouble;
    bAgeFirstSexLength: Integer;
    bIduShareProp: PDouble;
    bIduSharePropLength: Integer;
    epiInfectiousness: PDouble;
    epiInfectiousnessLength: Integer;
    epiInfMultArt: PDouble;
    epiInfMultArtLength: Integer;
    outNewInf: PDouble;
    outNewInfLength: Integer;
    epiTransmMultM: Double;
    epiTransmMultMLength: Integer;
    epiTransmHivF: Double;
    epiTransmHivFLength: Integer;
    epiTransmStiMult: Double;
    epiTransmStiMultLength: Integer;
    epiTransmMultMsm: Double;
    epiTransmMultMsmLength: Integer;
    epiCondomEffect: Double;
    epiCondomEffectLength: Integer;
    epiRedwhenCircum: PDouble;
    epiRedwhenCircumLength: Integer;
    epiStiPrev: PDouble;
    epiStiPrevLength: Integer;
    bFoiIdu: PDouble;
    bFoiIduLength: Integer;
    prepCov: PDouble;
    prepCovLength: Integer;
    prepMethodMix: PDouble;
    prepMethodMixLength: Integer;
    prepEffectiveness: PDouble;
    prepEffectivenessLength: Integer;
    rnCureEffect: PDouble;
    rnCureEffectLength: Integer;
    rnCureCoverageRg: PDouble;
    rnCureCoverageRgLength: Integer;
    rnCureCoverageAll: PDouble;
    rnCureCoverageAllLength: Integer;
    rnCureCoverageType: Integer;
    rnCureCoverageTypeLength: Integer;
    rnCoverage: PDouble;
    rnCoverageLength: Integer;
    rnPocCov: PDouble;
    rnPocCovLength: Integer;
    rnPocEffect: PDouble;
    rnPocEffectLength: Integer;
    rnAdhTreatCov: PDouble;
    rnAdhTreatCovLength: Integer;
    rnAdhTreatReducMort: Double;
    rnAdhTreatReducMortLength: Integer;
    rnVacParams: PDouble;
    rnVacParamsLength: Integer;
    rnVacCoverageRg: PDouble;
    rnVacCoverageRgLength: Integer;
    rnVacCoverageAll: PDouble;
    rnVacCoverageAllLength: Integer;
    rnVacCovType: Integer;
    rnVacCovTypeLength: Integer;
    rnVacTargetting: Integer;
    rnVacTargettingLength: Integer;
    rnUnitCosts: PDouble;
    rnUnitCostsLength: Integer;
    rnPopSizes: PDouble;
    rnPopSizesLength: Integer;
    hvImpactMatrix: PDouble;
    hvImpactMatrixLength: Integer;
    artCoverageRg: PDouble;
    artCoverageRgLength: Integer;
    artCovNumPercent: PInteger;
    artCovNumPercentLength: Integer;
end;

type
  LeapfrogGoalsParams = class
  public
    goalsBaseYearIdx: Integer;
    epiStartYear: Integer;
    epiMonthsInPrimary: Double;
    bBalanceSexActs: Integer;
    epiInitialPulse: Double;
    bCondomProp: TGBFixedArray<Double>;
    bBehavProperties: TGBFixedArray<Double>;
    bSexActs: TGBFixedArray<Double>;
    bNumPartners: TGBFixedArray<Double>;
    bIncrRecruit: TGBFixedArray<Double>;
    bMarriedProp: TGBFixedArray<Double>;
    bAgeFirstSex: TGBFixedArray<Double>;
    bIduShareProp: TGBFixedArray<Double>;
    epiInfectiousness: TGBFixedArray<Double>;
    epiInfMultArt: TGBFixedArray<Double>;
    outNewInf: TGBFixedArray<Double>;
    epiTransmMultM: Double;
    epiTransmHivF: Double;
    epiTransmStiMult: Double;
    epiTransmMultMsm: Double;
    epiCondomEffect: Double;
    epiRedwhenCircum: TGBFixedArray<Double>;
    epiStiPrev: TGBFixedArray<Double>;
    bFoiIdu: TGBFixedArray<Double>;
    prepCov: TGBFixedArray<Double>;
    prepMethodMix: TGBFixedArray<Double>;
    prepEffectiveness: TGBFixedArray<Double>;
    rnCureEffect: TGBFixedArray<Double>;
    rnCureCoverageRg: TGBFixedArray<Double>;
    rnCureCoverageAll: TGBFixedArray<Double>;
    rnCureCoverageType: Integer;
    rnCoverage: TGBFixedArray<Double>;
    rnPocCov: TGBFixedArray<Double>;
    rnPocEffect: TGBFixedArray<Double>;
    rnAdhTreatCov: TGBFixedArray<Double>;
    rnAdhTreatReducMort: Double;
    rnVacParams: TGBFixedArray<Double>;
    rnVacCoverageRg: TGBFixedArray<Double>;
    rnVacCoverageAll: TGBFixedArray<Double>;
    rnVacCovType: Integer;
    rnVacTargetting: Integer;
    rnUnitCosts: TGBFixedArray<Double>;
    rnPopSizes: TGBFixedArray<Double>;
    hvImpactMatrix: TGBFixedArray<Double>;
    artCoverageRg: TGBFixedArray<Double>;
    artCovNumPercent: TGBFixedArray<Integer>;
    function getView(): LeapfrogGoalsParamsView;
    procedure writeToDisk(dir: string);
    Destructor Destroy; override;
end;

{$ALIGN 8}
type
  LeapfrogGoalsStateView = record
  private
    totalPopulation: PDouble;
    totalPopulationLength: Integer;
    totalPopulationDp: PDouble;
    totalPopulationDpLength: Integer;
    adults: PDouble;
    adultsLength: Integer;
    adultsTs: PDouble;
    adultsTsLength: Integer;
    popHivNeg: PDouble;
    popHivNegLength: Integer;
    curedPop: PDouble;
    curedPopLength: Integer;
    curedProp: PDouble;
    curedPropLength: Integer;
    deaths: PDouble;
    deathsLength: Integer;
    totalDeaths: PDouble;
    totalDeathsLength: Integer;
    totalDeathsHiv: PDouble;
    totalDeathsHivLength: Integer;
    deathsHiv: PDouble;
    deathsHivLength: Integer;
    newInfections: PDouble;
    newInfectionsLength: Integer;
    totalNewInfections: PDouble;
    totalNewInfectionsLength: Integer;
    newInfectionsDp: PDouble;
    newInfectionsDpLength: Integer;
    incidenceGoals: PDouble;
    incidenceGoalsLength: Integer;
    newInfectionsGoals: PDouble;
    newInfectionsGoalsLength: Integer;
    prevalence: PDouble;
    prevalenceLength: Integer;
    totalPrevalence: PDouble;
    totalPrevalenceLength: Integer;
    newlyOnArt: PDouble;
    newlyOnArtLength: Integer;
    totalOnArt: PDouble;
    totalOnArtLength: Integer;
    totalPlhiv: PDouble;
    totalPlhivLength: Integer;
    multNoArt: PDouble;
    multNoArtLength: Integer;
    multArt: PDouble;
    multArtLength: Integer;
    newInfVrs: PDouble;
    newInfVrsLength: Integer;
    newInfS: PDouble;
    newInfSLength: Integer;
    numPeopleReached: PDouble;
    numPeopleReachedLength: Integer;
    resourcesRequired: PDouble;
    resourcesRequiredLength: Integer;
end;

type
  LeapfrogGoalsState = class
  public
    totalPopulation: TGBFixedArray<Double>;
    totalPopulationDp: TGBFixedArray<Double>;
    adults: TGBFixedArray<Double>;
    adultsTs: TGBFixedArray<Double>;
    popHivNeg: TGBFixedArray<Double>;
    curedPop: TGBFixedArray<Double>;
    curedProp: TGBFixedArray<Double>;
    deaths: TGBFixedArray<Double>;
    totalDeaths: TGBFixedArray<Double>;
    totalDeathsHiv: TGBFixedArray<Double>;
    deathsHiv: TGBFixedArray<Double>;
    newInfections: TGBFixedArray<Double>;
    totalNewInfections: TGBFixedArray<Double>;
    newInfectionsDp: TGBFixedArray<Double>;
    incidenceGoals: TGBFixedArray<Double>;
    newInfectionsGoals: TGBFixedArray<Double>;
    prevalence: TGBFixedArray<Double>;
    totalPrevalence: TGBFixedArray<Double>;
    newlyOnArt: TGBFixedArray<Double>;
    totalOnArt: TGBFixedArray<Double>;
    totalPlhiv: TGBFixedArray<Double>;
    multNoArt: TGBFixedArray<Double>;
    multArt: TGBFixedArray<Double>;
    newInfVrs: TGBFixedArray<Double>;
    newInfS: TGBFixedArray<Double>;
    numPeopleReached: TGBFixedArray<Double>;
    resourcesRequired: TGBFixedArray<Double>;
    function getView(): LeapfrogGoalsStateView;
    procedure writeToDisk(dir: string);
    Destructor Destroy; override;
end;

{$ALIGN 8}
type
  LeapfrogParams = record
  private
    demproj: ^LeapfrogDemProjParamsView;
    hivadult: ^LeapfrogHivAdultParamsView;
    hivchild: ^LeapfrogHivChildParamsView;
    spectrum: ^LeapfrogSpectrumParamsView;
    goals: ^LeapfrogGoalsParamsView;
  public
    procedure SetDemProjParams(const demprojParams: LeapfrogDemProjParamsView);
    procedure SetHivAdultParams(const hivadultParams: LeapfrogHivAdultParamsView);
    procedure SetHivChildParams(const hivchildParams: LeapfrogHivChildParamsView);
    procedure SetSpectrumParams(const spectrumParams: LeapfrogSpectrumParamsView);
    procedure SetGoalsParams(const goalsParams: LeapfrogGoalsParamsView);
end;

{$ALIGN 8}
type
  LeapfrogState = record
  private
    demproj: ^LeapfrogDemProjStateView;
    hivadult: ^LeapfrogHivAdultStateView;
    hivchild: ^LeapfrogHivChildStateView;
    spectrum: ^LeapfrogSpectrumStateView;
    goals: ^LeapfrogGoalsStateView;
  public
    procedure SetDemProjState(const demprojState: LeapfrogDemProjStateView);
    procedure SetHivAdultState(const hivadultState: LeapfrogHivAdultStateView);
    procedure SetHivChildState(const hivchildState: LeapfrogHivChildStateView);
    procedure SetSpectrumState(const spectrumState: LeapfrogSpectrumStateView);
    procedure SetGoalsState(const goalsState: LeapfrogGoalsStateView);
end;

type TCallbackFunction = procedure(Msg: PAnsiChar); stdcall;

procedure LeapfrogRunDp(const params: LeapfrogParams; const opts: LeapfrogOptions; const outputState: LeapfrogState; errorHandler: TCallbackFunction); safecall; external 'leapfrog.dll' name 'run_dp';
procedure LeapfrogRunAim(const params: LeapfrogParams; const opts: LeapfrogOptions; const outputState: LeapfrogState; errorHandler: TCallbackFunction); safecall; external 'leapfrog.dll' name 'run_aim';
procedure LeapfrogRunDpSingleYear(const params: LeapfrogParams; const opts: LeapfrogOptions; const initial_state: LeapfrogState; start_year: Integer; const state: LeapfrogState; errorHandler: TCallbackFunction); safecall; external 'leapfrog.dll' name 'run_dp_single_year';
procedure LeapfrogRunAimSingleYear(const params: LeapfrogParams; const opts: LeapfrogOptions; const initial_state: LeapfrogState; start_year: Integer; const state: LeapfrogState; errorHandler: TCallbackFunction); safecall; external 'leapfrog.dll' name 'run_aim_single_year';

implementation

destructor LeapfrogDemProjParams.Destroy;
begin;
  basePop.Free;
  survivalProbability.Free;
  netMigration.Free;
  ageSpecificFertilityRate.Free;
  birthsSexProp.Free;
  totalFertilityRate.Free;
  inherited;
end;

destructor LeapfrogDemProjState.Destroy;
begin;
  pTotpop.Free;
  pDeathsBackgroundTotpop.Free;
  births.Free;
  inherited;
end;

function LeapfrogDemProjParams.getView(): LeapfrogDemProjParamsView;
begin;
  Result.basePop := PDouble(basePop.data);
  Result.basePopLength := basePop.GetLength();
  Result.survivalProbability := PDouble(survivalProbability.data);
  Result.survivalProbabilityLength := survivalProbability.GetLength();
  Result.netMigration := PDouble(netMigration.data);
  Result.netMigrationLength := netMigration.GetLength();
  Result.ageSpecificFertilityRate := PDouble(ageSpecificFertilityRate.data);
  Result.ageSpecificFertilityRateLength := ageSpecificFertilityRate.GetLength();
  Result.birthsSexProp := PDouble(birthsSexProp.data);
  Result.birthsSexPropLength := birthsSexProp.GetLength();
  Result.totalFertilityRate := PDouble(totalFertilityRate.data);
  Result.totalFertilityRateLength := totalFertilityRate.GetLength();
end;

function LeapfrogDemProjState.getView(): LeapfrogDemProjStateView;
begin;
  Result.pTotpop := PDouble(pTotpop.data);
  Result.pTotpopLength := pTotpop.GetLength();
  Result.pDeathsBackgroundTotpop := PDouble(pDeathsBackgroundTotpop.data);
  Result.pDeathsBackgroundTotpopLength := pDeathsBackgroundTotpop.GetLength();
  Result.births := PDouble(births.data);
  Result.birthsLength := births.GetLength();
end;

destructor LeapfrogHivAdultParams.Destroy;
begin;
  inputAdultIncidenceRate.Free;
  transmissionRateHts.Free;
  incidenceRateRatioAge.Free;
  incidenceRateRatioSex.Free;
  cd4Mortality.Free;
  cd4Progression.Free;
  cd4InitialDistribution.Free;
  idxHmElig.Free;
  artMortality.Free;
  artMortalityTimeRateRatio.Free;
  cd4NonaidsExcessMort.Free;
  artNonaidsExcessMort.Free;
  dropoutRate.Free;
  adultsOnArt.Free;
  adultsOnArtIsPercent.Free;
  hArtStageDur.Free;
  fertMultByAge.Free;
  fertMultOffArt.Free;
  fertMultOnArt.Free;
  pwidPropHivpop.Free;
  pwidSexRatio.Free;
  inherited;
end;

destructor LeapfrogHivAdultState.Destroy;
begin;
  pHivpop.Free;
  pDeathsBackgroundHivpop.Free;
  hHivpop.Free;
  hArtpop.Free;
  hHivDeathsNoArt.Free;
  hDeathsExcessNonaidsNoArt.Free;
  pInfections.Free;
  hHivDeathsArt.Free;
  hDeathsExcessNonaidsOnArt.Free;
  hArtInitiation.Free;
  pHivDeaths.Free;
  pDeathsExcessNonaids.Free;
  pNetMigrationHivpop.Free;
  hivBirthsByMatAge.Free;
  hivBirths.Free;
  prevalence15to49Hts.Free;
  incidence15to49Hts.Free;
  artcoverage15to49Hts.Free;
  inherited;
end;

function LeapfrogHivAdultParams.getView(): LeapfrogHivAdultParamsView;
begin;
  Result.incidenceModelChoice := incidenceModelChoice;
  Result.incidenceModelChoiceLength := 1;
  Result.inputAdultIncidenceRate := PDouble(inputAdultIncidenceRate.data);
  Result.inputAdultIncidenceRateLength := inputAdultIncidenceRate.GetLength();
  Result.transmissionRateHts := PDouble(transmissionRateHts.data);
  Result.transmissionRateHtsLength := transmissionRateHts.GetLength();
  Result.initialIncidence := initialIncidence;
  Result.initialIncidenceLength := 1;
  Result.epidemicStartHts := epidemicStartHts;
  Result.epidemicStartHtsLength := 1;
  Result.relativeInfectiousnessArt := relativeInfectiousnessArt;
  Result.relativeInfectiousnessArtLength := 1;
  Result.incidenceRateRatioAge := PDouble(incidenceRateRatioAge.data);
  Result.incidenceRateRatioAgeLength := incidenceRateRatioAge.GetLength();
  Result.incidenceRateRatioSex := PDouble(incidenceRateRatioSex.data);
  Result.incidenceRateRatioSexLength := incidenceRateRatioSex.GetLength();
  Result.cd4Mortality := PDouble(cd4Mortality.data);
  Result.cd4MortalityLength := cd4Mortality.GetLength();
  Result.cd4Progression := PDouble(cd4Progression.data);
  Result.cd4ProgressionLength := cd4Progression.GetLength();
  Result.cd4InitialDistribution := PDouble(cd4InitialDistribution.data);
  Result.cd4InitialDistributionLength := cd4InitialDistribution.GetLength();
  Result.scaleCd4Mortality := scaleCd4Mortality;
  Result.scaleCd4MortalityLength := 1;
  Result.idxHmElig := PInteger(idxHmElig.data);
  Result.idxHmEligLength := idxHmElig.GetLength();
  Result.artMortality := PDouble(artMortality.data);
  Result.artMortalityLength := artMortality.GetLength();
  Result.artMortalityTimeRateRatio := PDouble(artMortalityTimeRateRatio.data);
  Result.artMortalityTimeRateRatioLength := artMortalityTimeRateRatio.GetLength();
  Result.cd4NonaidsExcessMort := PDouble(cd4NonaidsExcessMort.data);
  Result.cd4NonaidsExcessMortLength := cd4NonaidsExcessMort.GetLength();
  Result.artNonaidsExcessMort := PDouble(artNonaidsExcessMort.data);
  Result.artNonaidsExcessMortLength := artNonaidsExcessMort.GetLength();
  Result.dropoutRecoverCd4 := dropoutRecoverCd4;
  Result.dropoutRecoverCd4Length := 1;
  Result.dropoutRate := PDouble(dropoutRate.data);
  Result.dropoutRateLength := dropoutRate.GetLength();
  Result.adultsOnArt := PDouble(adultsOnArt.data);
  Result.adultsOnArtLength := adultsOnArt.GetLength();
  Result.adultsOnArtIsPercent := PInteger(adultsOnArtIsPercent.data);
  Result.adultsOnArtIsPercentLength := adultsOnArtIsPercent.GetLength();
  Result.initiationMortalityWeight := initiationMortalityWeight;
  Result.initiationMortalityWeightLength := 1;
  Result.hArtStageDur := PDouble(hArtStageDur.data);
  Result.hArtStageDurLength := hArtStageDur.GetLength();
  Result.pagIncidpop := pagIncidpop;
  Result.pagIncidpopLength := 1;
  Result.pidxIncidpop := pidxIncidpop;
  Result.pidxIncidpopLength := 1;
  Result.fertMultByAge := PDouble(fertMultByAge.data);
  Result.fertMultByAgeLength := fertMultByAge.GetLength();
  Result.fertMultOffArt := PDouble(fertMultOffArt.data);
  Result.fertMultOffArtLength := fertMultOffArt.GetLength();
  Result.fertMultOnArt := PDouble(fertMultOnArt.data);
  Result.fertMultOnArtLength := fertMultOnArt.GetLength();
  Result.localAdjFactor := localAdjFactor;
  Result.localAdjFactorLength := 1;
  Result.pwidHivposNonaidsMortality := pwidHivposNonaidsMortality;
  Result.pwidHivposNonaidsMortalityLength := 1;
  Result.pwidPropHivpop := PDouble(pwidPropHivpop.data);
  Result.pwidPropHivpopLength := pwidPropHivpop.GetLength();
  Result.pwidSexRatio := PDouble(pwidSexRatio.data);
  Result.pwidSexRatioLength := pwidSexRatio.GetLength();
end;

function LeapfrogHivAdultState.getView(): LeapfrogHivAdultStateView;
begin;
  Result.pHivpop := PDouble(pHivpop.data);
  Result.pHivpopLength := pHivpop.GetLength();
  Result.pDeathsBackgroundHivpop := PDouble(pDeathsBackgroundHivpop.data);
  Result.pDeathsBackgroundHivpopLength := pDeathsBackgroundHivpop.GetLength();
  Result.hHivpop := PDouble(hHivpop.data);
  Result.hHivpopLength := hHivpop.GetLength();
  Result.hArtpop := PDouble(hArtpop.data);
  Result.hArtpopLength := hArtpop.GetLength();
  Result.hHivDeathsNoArt := PDouble(hHivDeathsNoArt.data);
  Result.hHivDeathsNoArtLength := hHivDeathsNoArt.GetLength();
  Result.hDeathsExcessNonaidsNoArt := PDouble(hDeathsExcessNonaidsNoArt.data);
  Result.hDeathsExcessNonaidsNoArtLength := hDeathsExcessNonaidsNoArt.GetLength();
  Result.pInfections := PDouble(pInfections.data);
  Result.pInfectionsLength := pInfections.GetLength();
  Result.hHivDeathsArt := PDouble(hHivDeathsArt.data);
  Result.hHivDeathsArtLength := hHivDeathsArt.GetLength();
  Result.hDeathsExcessNonaidsOnArt := PDouble(hDeathsExcessNonaidsOnArt.data);
  Result.hDeathsExcessNonaidsOnArtLength := hDeathsExcessNonaidsOnArt.GetLength();
  Result.hArtInitiation := PDouble(hArtInitiation.data);
  Result.hArtInitiationLength := hArtInitiation.GetLength();
  Result.pHivDeaths := PDouble(pHivDeaths.data);
  Result.pHivDeathsLength := pHivDeaths.GetLength();
  Result.pDeathsExcessNonaids := PDouble(pDeathsExcessNonaids.data);
  Result.pDeathsExcessNonaidsLength := pDeathsExcessNonaids.GetLength();
  Result.pNetMigrationHivpop := PDouble(pNetMigrationHivpop.data);
  Result.pNetMigrationHivpopLength := pNetMigrationHivpop.GetLength();
  Result.hivBirthsByMatAge := PDouble(hivBirthsByMatAge.data);
  Result.hivBirthsByMatAgeLength := hivBirthsByMatAge.GetLength();
  Result.hivBirths := PDouble(hivBirths.data);
  Result.hivBirthsLength := hivBirths.GetLength();
  Result.prevalence15to49Hts := PDouble(prevalence15to49Hts.data);
  Result.prevalence15to49HtsLength := prevalence15to49Hts.GetLength();
  Result.incidence15to49Hts := PDouble(incidence15to49Hts.data);
  Result.incidence15to49HtsLength := incidence15to49Hts.GetLength();
  Result.artcoverage15to49Hts := PDouble(artcoverage15to49Hts.data);
  Result.artcoverage15to49HtsLength := artcoverage15to49Hts.GetLength();
end;

destructor LeapfrogHivChildParams.Destroy;
begin;
  hcNosocomialInfectionsByAge.Free;
  hc1Cd4Dist.Free;
  hc1Cd4Mort.Free;
  hc2Cd4Mort.Free;
  hc1Cd4Prog.Free;
  hc2Cd4Prog.Free;
  ctxVal.Free;
  hcArtEligAge.Free;
  hcArtEligCd4.Free;
  hcArtMortRr.Free;
  hc1ArtMort.Free;
  hc2ArtMort.Free;
  hcArtIsperc.Free;
  hcArtVal.Free;
  hcArtInitDist.Free;
  pmtct.Free;
  verticalTransmissionRate.Free;
  pmtctTransmissionRate.Free;
  pmtctDropout.Free;
  pmtctInputIsPercent.Free;
  breastfeedingDurationArt.Free;
  breastfeedingDurationNoArt.Free;
  infantPop.Free;
  matHivBirths.Free;
  matPrevInput.Free;
  propLt200.Free;
  propGte350.Free;
  ctxValIsPercent.Free;
  hcArtIsAgeSpec.Free;
  abortion.Free;
  patientsReallocated.Free;
  hcArtLtfu.Free;
  adultFemaleInfections.Free;
  adultFemaleHivnpop.Free;
  totalBirths.Free;
  ctxEffect.Free;
  hcAgeSpecificFertilityRate.Free;
  inherited;
end;

destructor LeapfrogHivChildState.Destroy;
begin;
  hc1Hivpop.Free;
  hc2Hivpop.Free;
  hc1Artpop.Free;
  hc2Artpop.Free;
  hc1NoartAidsDeaths.Free;
  hc2NoartAidsDeaths.Free;
  hc1ArtAidsDeaths.Free;
  hc2ArtAidsDeaths.Free;
  hcArtInit.Free;
  hcArtNeedInit.Free;
  ctxNeed.Free;
  infectionByType.Free;
  mtctBySourceTr.Free;
  mtctBySourceWomen.Free;
  mtctBySourceHcInfections.Free;
  pmtctCoverageAtDelivery.Free;
  inherited;
end;

function LeapfrogHivChildParams.getView(): LeapfrogHivChildParamsView;
begin;
  Result.hcNosocomialInfectionsByAge := PDouble(hcNosocomialInfectionsByAge.data);
  Result.hcNosocomialInfectionsByAgeLength := hcNosocomialInfectionsByAge.GetLength();
  Result.hc1Cd4Dist := PDouble(hc1Cd4Dist.data);
  Result.hc1Cd4DistLength := hc1Cd4Dist.GetLength();
  Result.hc1Cd4Mort := PDouble(hc1Cd4Mort.data);
  Result.hc1Cd4MortLength := hc1Cd4Mort.GetLength();
  Result.hc2Cd4Mort := PDouble(hc2Cd4Mort.data);
  Result.hc2Cd4MortLength := hc2Cd4Mort.GetLength();
  Result.hc1Cd4Prog := PDouble(hc1Cd4Prog.data);
  Result.hc1Cd4ProgLength := hc1Cd4Prog.GetLength();
  Result.hc2Cd4Prog := PDouble(hc2Cd4Prog.data);
  Result.hc2Cd4ProgLength := hc2Cd4Prog.GetLength();
  Result.ctxVal := PDouble(ctxVal.data);
  Result.ctxValLength := ctxVal.GetLength();
  Result.hcArtEligAge := PInteger(hcArtEligAge.data);
  Result.hcArtEligAgeLength := hcArtEligAge.GetLength();
  Result.hcArtEligCd4 := PInteger(hcArtEligCd4.data);
  Result.hcArtEligCd4Length := hcArtEligCd4.GetLength();
  Result.hcArtMortRr := PDouble(hcArtMortRr.data);
  Result.hcArtMortRrLength := hcArtMortRr.GetLength();
  Result.hc1ArtMort := PDouble(hc1ArtMort.data);
  Result.hc1ArtMortLength := hc1ArtMort.GetLength();
  Result.hc2ArtMort := PDouble(hc2ArtMort.data);
  Result.hc2ArtMortLength := hc2ArtMort.GetLength();
  Result.hcArtIsperc := PInteger(hcArtIsperc.data);
  Result.hcArtIspercLength := hcArtIsperc.GetLength();
  Result.hcArtVal := PDouble(hcArtVal.data);
  Result.hcArtValLength := hcArtVal.GetLength();
  Result.hcArtInitDist := PDouble(hcArtInitDist.data);
  Result.hcArtInitDistLength := hcArtInitDist.GetLength();
  Result.pmtct := PDouble(pmtct.data);
  Result.pmtctLength := pmtct.GetLength();
  Result.verticalTransmissionRate := PDouble(verticalTransmissionRate.data);
  Result.verticalTransmissionRateLength := verticalTransmissionRate.GetLength();
  Result.pmtctTransmissionRate := PDouble(pmtctTransmissionRate.data);
  Result.pmtctTransmissionRateLength := pmtctTransmissionRate.GetLength();
  Result.pmtctDropout := PDouble(pmtctDropout.data);
  Result.pmtctDropoutLength := pmtctDropout.GetLength();
  Result.pmtctInputIsPercent := PInteger(pmtctInputIsPercent.data);
  Result.pmtctInputIsPercentLength := pmtctInputIsPercent.GetLength();
  Result.breastfeedingDurationArt := PDouble(breastfeedingDurationArt.data);
  Result.breastfeedingDurationArtLength := breastfeedingDurationArt.GetLength();
  Result.breastfeedingDurationNoArt := PDouble(breastfeedingDurationNoArt.data);
  Result.breastfeedingDurationNoArtLength := breastfeedingDurationNoArt.GetLength();
  Result.infantPop := PDouble(infantPop.data);
  Result.infantPopLength := infantPop.GetLength();
  Result.matHivBirths := PDouble(matHivBirths.data);
  Result.matHivBirthsLength := matHivBirths.GetLength();
  Result.matPrevInput := PInteger(matPrevInput.data);
  Result.matPrevInputLength := matPrevInput.GetLength();
  Result.propLt200 := PDouble(propLt200.data);
  Result.propLt200Length := propLt200.GetLength();
  Result.propGte350 := PDouble(propGte350.data);
  Result.propGte350Length := propGte350.GetLength();
  Result.ctxValIsPercent := PInteger(ctxValIsPercent.data);
  Result.ctxValIsPercentLength := ctxValIsPercent.GetLength();
  Result.hcArtIsAgeSpec := PInteger(hcArtIsAgeSpec.data);
  Result.hcArtIsAgeSpecLength := hcArtIsAgeSpec.GetLength();
  Result.abortion := PDouble(abortion.data);
  Result.abortionLength := abortion.GetLength();
  Result.patientsReallocated := PDouble(patientsReallocated.data);
  Result.patientsReallocatedLength := patientsReallocated.GetLength();
  Result.hcArtLtfu := PDouble(hcArtLtfu.data);
  Result.hcArtLtfuLength := hcArtLtfu.GetLength();
  Result.adultFemaleInfections := PDouble(adultFemaleInfections.data);
  Result.adultFemaleInfectionsLength := adultFemaleInfections.GetLength();
  Result.adultFemaleHivnpop := PDouble(adultFemaleHivnpop.data);
  Result.adultFemaleHivnpopLength := adultFemaleHivnpop.GetLength();
  Result.totalBirths := PDouble(totalBirths.data);
  Result.totalBirthsLength := totalBirths.GetLength();
  Result.ctxEffect := PDouble(ctxEffect.data);
  Result.ctxEffectLength := ctxEffect.GetLength();
  Result.hcArtStart := hcArtStart;
  Result.hcArtStartLength := 1;
  Result.hcAgeSpecificFertilityRate := PDouble(hcAgeSpecificFertilityRate.data);
  Result.hcAgeSpecificFertilityRateLength := hcAgeSpecificFertilityRate.GetLength();
end;

function LeapfrogHivChildState.getView(): LeapfrogHivChildStateView;
begin;
  Result.hc1Hivpop := PDouble(hc1Hivpop.data);
  Result.hc1HivpopLength := hc1Hivpop.GetLength();
  Result.hc2Hivpop := PDouble(hc2Hivpop.data);
  Result.hc2HivpopLength := hc2Hivpop.GetLength();
  Result.hc1Artpop := PDouble(hc1Artpop.data);
  Result.hc1ArtpopLength := hc1Artpop.GetLength();
  Result.hc2Artpop := PDouble(hc2Artpop.data);
  Result.hc2ArtpopLength := hc2Artpop.GetLength();
  Result.hc1NoartAidsDeaths := PDouble(hc1NoartAidsDeaths.data);
  Result.hc1NoartAidsDeathsLength := hc1NoartAidsDeaths.GetLength();
  Result.hc2NoartAidsDeaths := PDouble(hc2NoartAidsDeaths.data);
  Result.hc2NoartAidsDeathsLength := hc2NoartAidsDeaths.GetLength();
  Result.hc1ArtAidsDeaths := PDouble(hc1ArtAidsDeaths.data);
  Result.hc1ArtAidsDeathsLength := hc1ArtAidsDeaths.GetLength();
  Result.hc2ArtAidsDeaths := PDouble(hc2ArtAidsDeaths.data);
  Result.hc2ArtAidsDeathsLength := hc2ArtAidsDeaths.GetLength();
  Result.hcArtInit := PDouble(hcArtInit.data);
  Result.hcArtInitLength := hcArtInit.GetLength();
  Result.hcArtNeedInit := PDouble(hcArtNeedInit.data);
  Result.hcArtNeedInitLength := hcArtNeedInit.GetLength();
  Result.ctxNeed := PDouble(ctxNeed.data);
  Result.ctxNeedLength := ctxNeed.GetLength();
  Result.infectionByType := PDouble(infectionByType.data);
  Result.infectionByTypeLength := infectionByType.GetLength();
  Result.mtctBySourceTr := PDouble(mtctBySourceTr.data);
  Result.mtctBySourceTrLength := mtctBySourceTr.GetLength();
  Result.mtctBySourceWomen := PDouble(mtctBySourceWomen.data);
  Result.mtctBySourceWomenLength := mtctBySourceWomen.GetLength();
  Result.mtctBySourceHcInfections := PDouble(mtctBySourceHcInfections.data);
  Result.mtctBySourceHcInfectionsLength := mtctBySourceHcInfections.GetLength();
  Result.pmtctCoverageAtDelivery := PDouble(pmtctCoverageAtDelivery.data);
  Result.pmtctCoverageAtDeliveryLength := pmtctCoverageAtDelivery.GetLength();
end;

destructor LeapfrogSpectrumParams.Destroy;
begin;
  inherited;
end;

destructor LeapfrogSpectrumState.Destroy;
begin;
  pDeathsNonaidsArtpop.Free;
  pDeathsNonaidsHivpop.Free;
  pExcessDeathsNonaidsOnArt.Free;
  pExcessDeathsNonaidsNoArt.Free;
  inherited;
end;

function LeapfrogSpectrumParams.getView(): LeapfrogSpectrumParamsView;
begin;
end;

function LeapfrogSpectrumState.getView(): LeapfrogSpectrumStateView;
begin;
  Result.pDeathsNonaidsArtpop := PDouble(pDeathsNonaidsArtpop.data);
  Result.pDeathsNonaidsArtpopLength := pDeathsNonaidsArtpop.GetLength();
  Result.pDeathsNonaidsHivpop := PDouble(pDeathsNonaidsHivpop.data);
  Result.pDeathsNonaidsHivpopLength := pDeathsNonaidsHivpop.GetLength();
  Result.pExcessDeathsNonaidsOnArt := PDouble(pExcessDeathsNonaidsOnArt.data);
  Result.pExcessDeathsNonaidsOnArtLength := pExcessDeathsNonaidsOnArt.GetLength();
  Result.pExcessDeathsNonaidsNoArt := PDouble(pExcessDeathsNonaidsNoArt.data);
  Result.pExcessDeathsNonaidsNoArtLength := pExcessDeathsNonaidsNoArt.GetLength();
end;

destructor LeapfrogGoalsParams.Destroy;
begin;
  bCondomProp.Free;
  bBehavProperties.Free;
  bSexActs.Free;
  bNumPartners.Free;
  bIncrRecruit.Free;
  bMarriedProp.Free;
  bAgeFirstSex.Free;
  bIduShareProp.Free;
  epiInfectiousness.Free;
  epiInfMultArt.Free;
  outNewInf.Free;
  epiRedwhenCircum.Free;
  epiStiPrev.Free;
  bFoiIdu.Free;
  prepCov.Free;
  prepMethodMix.Free;
  prepEffectiveness.Free;
  rnCureEffect.Free;
  rnCureCoverageRg.Free;
  rnCureCoverageAll.Free;
  rnCoverage.Free;
  rnPocCov.Free;
  rnPocEffect.Free;
  rnAdhTreatCov.Free;
  rnVacParams.Free;
  rnVacCoverageRg.Free;
  rnVacCoverageAll.Free;
  rnUnitCosts.Free;
  rnPopSizes.Free;
  hvImpactMatrix.Free;
  artCoverageRg.Free;
  artCovNumPercent.Free;
  inherited;
end;

destructor LeapfrogGoalsState.Destroy;
begin;
  totalPopulation.Free;
  totalPopulationDp.Free;
  adults.Free;
  adultsTs.Free;
  popHivNeg.Free;
  curedPop.Free;
  curedProp.Free;
  deaths.Free;
  totalDeaths.Free;
  totalDeathsHiv.Free;
  deathsHiv.Free;
  newInfections.Free;
  totalNewInfections.Free;
  newInfectionsDp.Free;
  incidenceGoals.Free;
  newInfectionsGoals.Free;
  prevalence.Free;
  totalPrevalence.Free;
  newlyOnArt.Free;
  totalOnArt.Free;
  totalPlhiv.Free;
  multNoArt.Free;
  multArt.Free;
  newInfVrs.Free;
  newInfS.Free;
  numPeopleReached.Free;
  resourcesRequired.Free;
  inherited;
end;

function LeapfrogGoalsParams.getView(): LeapfrogGoalsParamsView;
begin;
  Result.goalsBaseYearIdx := goalsBaseYearIdx;
  Result.goalsBaseYearIdxLength := 1;
  Result.epiStartYear := epiStartYear;
  Result.epiStartYearLength := 1;
  Result.epiMonthsInPrimary := epiMonthsInPrimary;
  Result.epiMonthsInPrimaryLength := 1;
  Result.bBalanceSexActs := bBalanceSexActs;
  Result.bBalanceSexActsLength := 1;
  Result.epiInitialPulse := epiInitialPulse;
  Result.epiInitialPulseLength := 1;
  Result.bCondomProp := PDouble(bCondomProp.data);
  Result.bCondomPropLength := bCondomProp.GetLength();
  Result.bBehavProperties := PDouble(bBehavProperties.data);
  Result.bBehavPropertiesLength := bBehavProperties.GetLength();
  Result.bSexActs := PDouble(bSexActs.data);
  Result.bSexActsLength := bSexActs.GetLength();
  Result.bNumPartners := PDouble(bNumPartners.data);
  Result.bNumPartnersLength := bNumPartners.GetLength();
  Result.bIncrRecruit := PDouble(bIncrRecruit.data);
  Result.bIncrRecruitLength := bIncrRecruit.GetLength();
  Result.bMarriedProp := PDouble(bMarriedProp.data);
  Result.bMarriedPropLength := bMarriedProp.GetLength();
  Result.bAgeFirstSex := PDouble(bAgeFirstSex.data);
  Result.bAgeFirstSexLength := bAgeFirstSex.GetLength();
  Result.bIduShareProp := PDouble(bIduShareProp.data);
  Result.bIduSharePropLength := bIduShareProp.GetLength();
  Result.epiInfectiousness := PDouble(epiInfectiousness.data);
  Result.epiInfectiousnessLength := epiInfectiousness.GetLength();
  Result.epiInfMultArt := PDouble(epiInfMultArt.data);
  Result.epiInfMultArtLength := epiInfMultArt.GetLength();
  Result.outNewInf := PDouble(outNewInf.data);
  Result.outNewInfLength := outNewInf.GetLength();
  Result.epiTransmMultM := epiTransmMultM;
  Result.epiTransmMultMLength := 1;
  Result.epiTransmHivF := epiTransmHivF;
  Result.epiTransmHivFLength := 1;
  Result.epiTransmStiMult := epiTransmStiMult;
  Result.epiTransmStiMultLength := 1;
  Result.epiTransmMultMsm := epiTransmMultMsm;
  Result.epiTransmMultMsmLength := 1;
  Result.epiCondomEffect := epiCondomEffect;
  Result.epiCondomEffectLength := 1;
  Result.epiRedwhenCircum := PDouble(epiRedwhenCircum.data);
  Result.epiRedwhenCircumLength := epiRedwhenCircum.GetLength();
  Result.epiStiPrev := PDouble(epiStiPrev.data);
  Result.epiStiPrevLength := epiStiPrev.GetLength();
  Result.bFoiIdu := PDouble(bFoiIdu.data);
  Result.bFoiIduLength := bFoiIdu.GetLength();
  Result.prepCov := PDouble(prepCov.data);
  Result.prepCovLength := prepCov.GetLength();
  Result.prepMethodMix := PDouble(prepMethodMix.data);
  Result.prepMethodMixLength := prepMethodMix.GetLength();
  Result.prepEffectiveness := PDouble(prepEffectiveness.data);
  Result.prepEffectivenessLength := prepEffectiveness.GetLength();
  Result.rnCureEffect := PDouble(rnCureEffect.data);
  Result.rnCureEffectLength := rnCureEffect.GetLength();
  Result.rnCureCoverageRg := PDouble(rnCureCoverageRg.data);
  Result.rnCureCoverageRgLength := rnCureCoverageRg.GetLength();
  Result.rnCureCoverageAll := PDouble(rnCureCoverageAll.data);
  Result.rnCureCoverageAllLength := rnCureCoverageAll.GetLength();
  Result.rnCureCoverageType := rnCureCoverageType;
  Result.rnCureCoverageTypeLength := 1;
  Result.rnCoverage := PDouble(rnCoverage.data);
  Result.rnCoverageLength := rnCoverage.GetLength();
  Result.rnPocCov := PDouble(rnPocCov.data);
  Result.rnPocCovLength := rnPocCov.GetLength();
  Result.rnPocEffect := PDouble(rnPocEffect.data);
  Result.rnPocEffectLength := rnPocEffect.GetLength();
  Result.rnAdhTreatCov := PDouble(rnAdhTreatCov.data);
  Result.rnAdhTreatCovLength := rnAdhTreatCov.GetLength();
  Result.rnAdhTreatReducMort := rnAdhTreatReducMort;
  Result.rnAdhTreatReducMortLength := 1;
  Result.rnVacParams := PDouble(rnVacParams.data);
  Result.rnVacParamsLength := rnVacParams.GetLength();
  Result.rnVacCoverageRg := PDouble(rnVacCoverageRg.data);
  Result.rnVacCoverageRgLength := rnVacCoverageRg.GetLength();
  Result.rnVacCoverageAll := PDouble(rnVacCoverageAll.data);
  Result.rnVacCoverageAllLength := rnVacCoverageAll.GetLength();
  Result.rnVacCovType := rnVacCovType;
  Result.rnVacCovTypeLength := 1;
  Result.rnVacTargetting := rnVacTargetting;
  Result.rnVacTargettingLength := 1;
  Result.rnUnitCosts := PDouble(rnUnitCosts.data);
  Result.rnUnitCostsLength := rnUnitCosts.GetLength();
  Result.rnPopSizes := PDouble(rnPopSizes.data);
  Result.rnPopSizesLength := rnPopSizes.GetLength();
  Result.hvImpactMatrix := PDouble(hvImpactMatrix.data);
  Result.hvImpactMatrixLength := hvImpactMatrix.GetLength();
  Result.artCoverageRg := PDouble(artCoverageRg.data);
  Result.artCoverageRgLength := artCoverageRg.GetLength();
  Result.artCovNumPercent := PInteger(artCovNumPercent.data);
  Result.artCovNumPercentLength := artCovNumPercent.GetLength();
end;

function LeapfrogGoalsState.getView(): LeapfrogGoalsStateView;
begin;
  Result.totalPopulation := PDouble(totalPopulation.data);
  Result.totalPopulationLength := totalPopulation.GetLength();
  Result.totalPopulationDp := PDouble(totalPopulationDp.data);
  Result.totalPopulationDpLength := totalPopulationDp.GetLength();
  Result.adults := PDouble(adults.data);
  Result.adultsLength := adults.GetLength();
  Result.adultsTs := PDouble(adultsTs.data);
  Result.adultsTsLength := adultsTs.GetLength();
  Result.popHivNeg := PDouble(popHivNeg.data);
  Result.popHivNegLength := popHivNeg.GetLength();
  Result.curedPop := PDouble(curedPop.data);
  Result.curedPopLength := curedPop.GetLength();
  Result.curedProp := PDouble(curedProp.data);
  Result.curedPropLength := curedProp.GetLength();
  Result.deaths := PDouble(deaths.data);
  Result.deathsLength := deaths.GetLength();
  Result.totalDeaths := PDouble(totalDeaths.data);
  Result.totalDeathsLength := totalDeaths.GetLength();
  Result.totalDeathsHiv := PDouble(totalDeathsHiv.data);
  Result.totalDeathsHivLength := totalDeathsHiv.GetLength();
  Result.deathsHiv := PDouble(deathsHiv.data);
  Result.deathsHivLength := deathsHiv.GetLength();
  Result.newInfections := PDouble(newInfections.data);
  Result.newInfectionsLength := newInfections.GetLength();
  Result.totalNewInfections := PDouble(totalNewInfections.data);
  Result.totalNewInfectionsLength := totalNewInfections.GetLength();
  Result.newInfectionsDp := PDouble(newInfectionsDp.data);
  Result.newInfectionsDpLength := newInfectionsDp.GetLength();
  Result.incidenceGoals := PDouble(incidenceGoals.data);
  Result.incidenceGoalsLength := incidenceGoals.GetLength();
  Result.newInfectionsGoals := PDouble(newInfectionsGoals.data);
  Result.newInfectionsGoalsLength := newInfectionsGoals.GetLength();
  Result.prevalence := PDouble(prevalence.data);
  Result.prevalenceLength := prevalence.GetLength();
  Result.totalPrevalence := PDouble(totalPrevalence.data);
  Result.totalPrevalenceLength := totalPrevalence.GetLength();
  Result.newlyOnArt := PDouble(newlyOnArt.data);
  Result.newlyOnArtLength := newlyOnArt.GetLength();
  Result.totalOnArt := PDouble(totalOnArt.data);
  Result.totalOnArtLength := totalOnArt.GetLength();
  Result.totalPlhiv := PDouble(totalPlhiv.data);
  Result.totalPlhivLength := totalPlhiv.GetLength();
  Result.multNoArt := PDouble(multNoArt.data);
  Result.multNoArtLength := multNoArt.GetLength();
  Result.multArt := PDouble(multArt.data);
  Result.multArtLength := multArt.GetLength();
  Result.newInfVrs := PDouble(newInfVrs.data);
  Result.newInfVrsLength := newInfVrs.GetLength();
  Result.newInfS := PDouble(newInfS.data);
  Result.newInfSLength := newInfS.GetLength();
  Result.numPeopleReached := PDouble(numPeopleReached.data);
  Result.numPeopleReachedLength := numPeopleReached.GetLength();
  Result.resourcesRequired := PDouble(resourcesRequired.data);
  Result.resourcesRequiredLength := resourcesRequired.GetLength();
end;

procedure LeapfrogDemProjParams.writeToDisk(dir: string);
begin;
  if not DirectoryExists(dir) then
    ForceDirectories(dir);
  basePop.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'basePop');
  survivalProbability.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'survivalProbability');
  netMigration.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'netMigration');
  ageSpecificFertilityRate.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'ageSpecificFertilityRate');
  birthsSexProp.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'birthsSexProp');
  totalFertilityRate.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'totalFertilityRate');
end;

procedure LeapfrogDemProjState.writeToDisk(dir: string);
begin;
  if not DirectoryExists(dir) then
    ForceDirectories(dir);
  pTotpop.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pTotpop');
  pDeathsBackgroundTotpop.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pDeathsBackgroundTotpop');
end;

procedure LeapfrogHivAdultParams.writeToDisk(dir: string);
begin;
  if not DirectoryExists(dir) then
    ForceDirectories(dir);
  inputAdultIncidenceRate.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'inputAdultIncidenceRate');
  transmissionRateHts.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'transmissionRateHts');
  incidenceRateRatioAge.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'incidenceRateRatioAge');
  incidenceRateRatioSex.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'incidenceRateRatioSex');
  cd4Mortality.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'cd4Mortality');
  cd4Progression.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'cd4Progression');
  cd4InitialDistribution.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'cd4InitialDistribution');
  idxHmElig.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'idxHmElig');
  artMortality.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'artMortality');
  artMortalityTimeRateRatio.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'artMortalityTimeRateRatio');
  cd4NonaidsExcessMort.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'cd4NonaidsExcessMort');
  artNonaidsExcessMort.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'artNonaidsExcessMort');
  dropoutRate.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'dropoutRate');
  adultsOnArt.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'adultsOnArt');
  adultsOnArtIsPercent.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'adultsOnArtIsPercent');
  hArtStageDur.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hArtStageDur');
  fertMultByAge.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'fertMultByAge');
  fertMultOffArt.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'fertMultOffArt');
  fertMultOnArt.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'fertMultOnArt');
  pwidPropHivpop.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pwidPropHivpop');
  pwidSexRatio.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pwidSexRatio');
end;

procedure LeapfrogHivAdultState.writeToDisk(dir: string);
begin;
  if not DirectoryExists(dir) then
    ForceDirectories(dir);
  pHivpop.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pHivpop');
  pDeathsBackgroundHivpop.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pDeathsBackgroundHivpop');
  hHivpop.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hHivpop');
  hArtpop.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hArtpop');
  hHivDeathsNoArt.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hHivDeathsNoArt');
  hDeathsExcessNonaidsNoArt.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hDeathsExcessNonaidsNoArt');
  pInfections.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pInfections');
  hHivDeathsArt.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hHivDeathsArt');
  hDeathsExcessNonaidsOnArt.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hDeathsExcessNonaidsOnArt');
  hArtInitiation.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hArtInitiation');
  pHivDeaths.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pHivDeaths');
  pDeathsExcessNonaids.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pDeathsExcessNonaids');
  pNetMigrationHivpop.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pNetMigrationHivpop');
  hivBirthsByMatAge.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hivBirthsByMatAge');
  prevalence15to49Hts.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'prevalence15to49Hts');
  incidence15to49Hts.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'incidence15to49Hts');
  artcoverage15to49Hts.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'artcoverage15to49Hts');
end;

procedure LeapfrogHivChildParams.writeToDisk(dir: string);
begin;
  if not DirectoryExists(dir) then
    ForceDirectories(dir);
  hcNosocomialInfectionsByAge.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hcNosocomialInfectionsByAge');
  hc1Cd4Dist.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hc1Cd4Dist');
  hc1Cd4Mort.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hc1Cd4Mort');
  hc2Cd4Mort.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hc2Cd4Mort');
  hc1Cd4Prog.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hc1Cd4Prog');
  hc2Cd4Prog.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hc2Cd4Prog');
  ctxVal.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'ctxVal');
  hcArtEligAge.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hcArtEligAge');
  hcArtEligCd4.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hcArtEligCd4');
  hcArtMortRr.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hcArtMortRr');
  hc1ArtMort.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hc1ArtMort');
  hc2ArtMort.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hc2ArtMort');
  hcArtIsperc.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hcArtIsperc');
  hcArtVal.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hcArtVal');
  hcArtInitDist.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hcArtInitDist');
  pmtct.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pmtct');
  verticalTransmissionRate.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'verticalTransmissionRate');
  pmtctTransmissionRate.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pmtctTransmissionRate');
  pmtctDropout.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pmtctDropout');
  pmtctInputIsPercent.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pmtctInputIsPercent');
  breastfeedingDurationArt.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'breastfeedingDurationArt');
  breastfeedingDurationNoArt.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'breastfeedingDurationNoArt');
  infantPop.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'infantPop');
  matHivBirths.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'matHivBirths');
  matPrevInput.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'matPrevInput');
  propLt200.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'propLt200');
  propGte350.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'propGte350');
  ctxValIsPercent.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'ctxValIsPercent');
  hcArtIsAgeSpec.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hcArtIsAgeSpec');
  abortion.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'abortion');
  patientsReallocated.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'patientsReallocated');
  hcArtLtfu.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hcArtLtfu');
  adultFemaleInfections.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'adultFemaleInfections');
  adultFemaleHivnpop.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'adultFemaleHivnpop');
  totalBirths.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'totalBirths');
  ctxEffect.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'ctxEffect');
  hcAgeSpecificFertilityRate.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hcAgeSpecificFertilityRate');
end;

procedure LeapfrogHivChildState.writeToDisk(dir: string);
begin;
  if not DirectoryExists(dir) then
    ForceDirectories(dir);
  hc1Hivpop.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hc1Hivpop');
  hc2Hivpop.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hc2Hivpop');
  hc1Artpop.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hc1Artpop');
  hc2Artpop.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hc2Artpop');
  hc1NoartAidsDeaths.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hc1NoartAidsDeaths');
  hc2NoartAidsDeaths.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hc2NoartAidsDeaths');
  hc1ArtAidsDeaths.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hc1ArtAidsDeaths');
  hc2ArtAidsDeaths.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hc2ArtAidsDeaths');
  hcArtInit.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hcArtInit');
  hcArtNeedInit.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hcArtNeedInit');
  infectionByType.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'infectionByType');
  mtctBySourceTr.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'mtctBySourceTr');
  mtctBySourceWomen.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'mtctBySourceWomen');
  mtctBySourceHcInfections.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'mtctBySourceHcInfections');
  pmtctCoverageAtDelivery.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pmtctCoverageAtDelivery');
end;

procedure LeapfrogSpectrumParams.writeToDisk(dir: string);
begin;
  if not DirectoryExists(dir) then
    ForceDirectories(dir);
end;

procedure LeapfrogSpectrumState.writeToDisk(dir: string);
begin;
  if not DirectoryExists(dir) then
    ForceDirectories(dir);
  pDeathsNonaidsArtpop.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pDeathsNonaidsArtpop');
  pDeathsNonaidsHivpop.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pDeathsNonaidsHivpop');
  pExcessDeathsNonaidsOnArt.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pExcessDeathsNonaidsOnArt');
  pExcessDeathsNonaidsNoArt.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'pExcessDeathsNonaidsNoArt');
end;

procedure LeapfrogGoalsParams.writeToDisk(dir: string);
begin;
  if not DirectoryExists(dir) then
    ForceDirectories(dir);
  bCondomProp.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'bCondomProp');
  bBehavProperties.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'bBehavProperties');
  bSexActs.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'bSexActs');
  bNumPartners.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'bNumPartners');
  bIncrRecruit.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'bIncrRecruit');
  bMarriedProp.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'bMarriedProp');
  bAgeFirstSex.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'bAgeFirstSex');
  bIduShareProp.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'bIduShareProp');
  epiInfectiousness.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'epiInfectiousness');
  epiInfMultArt.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'epiInfMultArt');
  outNewInf.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'outNewInf');
  epiRedwhenCircum.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'epiRedwhenCircum');
  epiStiPrev.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'epiStiPrev');
  bFoiIdu.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'bFoiIdu');
  prepCov.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'prepCov');
  prepMethodMix.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'prepMethodMix');
  prepEffectiveness.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'prepEffectiveness');
  rnCureEffect.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'rnCureEffect');
  rnCureCoverageRg.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'rnCureCoverageRg');
  rnCureCoverageAll.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'rnCureCoverageAll');
  rnCoverage.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'rnCoverage');
  rnPocCov.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'rnPocCov');
  rnPocEffect.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'rnPocEffect');
  rnAdhTreatCov.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'rnAdhTreatCov');
  rnVacParams.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'rnVacParams');
  rnVacCoverageRg.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'rnVacCoverageRg');
  rnVacCoverageAll.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'rnVacCoverageAll');
  rnUnitCosts.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'rnUnitCosts');
  rnPopSizes.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'rnPopSizes');
  hvImpactMatrix.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'hvImpactMatrix');
  artCoverageRg.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'artCoverageRg');
  artCovNumPercent.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'artCovNumPercent');
end;

procedure LeapfrogGoalsState.writeToDisk(dir: string);
begin;
  if not DirectoryExists(dir) then
    ForceDirectories(dir);
  adults.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'adults');
  adultsTs.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'adultsTs');
  popHivNeg.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'popHivNeg');
  curedPop.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'curedPop');
  curedProp.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'curedProp');
  deaths.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'deaths');
  deathsHiv.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'deathsHiv');
  newInfections.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'newInfections');
  incidenceGoals.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'incidenceGoals');
  newInfectionsGoals.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'newInfectionsGoals');
  prevalence.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'prevalence');
  newlyOnArt.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'newlyOnArt');
  multNoArt.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'multNoArt');
  multArt.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'multArt');
  newInfVrs.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'newInfVrs');
  newInfS.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'newInfS');
  numPeopleReached.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'numPeopleReached');
  resourcesRequired.WriteToDisk(IncludeTrailingPathDelimiter(dir) +  'resourcesRequired');
end;

procedure LeapfrogParams.SetDemProjParams(const demprojParams: LeapfrogDemProjParamsView);
begin
  demproj := @demprojParams;
end;

procedure LeapfrogState.SetDemProjState(const demprojState: LeapfrogDemProjStateView);
begin
  demproj := @demprojState;
end;

procedure LeapfrogParams.SetHivAdultParams(const hivadultParams: LeapfrogHivAdultParamsView);
begin
  hivadult := @hivadultParams;
end;

procedure LeapfrogState.SetHivAdultState(const hivadultState: LeapfrogHivAdultStateView);
begin
  hivadult := @hivadultState;
end;

procedure LeapfrogParams.SetHivChildParams(const hivchildParams: LeapfrogHivChildParamsView);
begin
  hivchild := @hivchildParams;
end;

procedure LeapfrogState.SetHivChildState(const hivchildState: LeapfrogHivChildStateView);
begin
  hivchild := @hivchildState;
end;

procedure LeapfrogParams.SetSpectrumParams(const spectrumParams: LeapfrogSpectrumParamsView);
begin
  spectrum := @spectrumParams;
end;

procedure LeapfrogState.SetSpectrumState(const spectrumState: LeapfrogSpectrumStateView);
begin
  spectrum := @spectrumState;
end;

procedure LeapfrogParams.SetGoalsParams(const goalsParams: LeapfrogGoalsParamsView);
begin
  goals := @goalsParams;
end;

procedure LeapfrogState.SetGoalsState(const goalsState: LeapfrogGoalsStateView);
begin
  goals := @goalsState;
end;

end.
