name: leapfrog-py test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/py-package-test.yaml
    with:
      package_dir: leapfrog-py
      import_name: leapfrog_py
